version: '3.8'

services:
  backend:
    build: ./backend
    container_name: php_backend
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - ./env
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rushi@123
      MYSQL_DATABASE: app_db
      MYSQL_USER: rushi
      MYSQL_PASSWORD: Rushi@234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./front-end  # This points to your front-end directory
    container_name: frontend_app
    ports:
      - "3000:80"  # Exposes frontend on port 3000
    volumes:
      - ./front-end:/usr/share/nginx/html  # Maps your frontend files to Nginx's public directory
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
