# version: '3.8'

# services:
#   backend:
#     build: ./backend
#     container_name: php_backend
#     ports:
#       - "8080:80"
#     depends_on:
#       - db
#     # env_file:
#     #   - ./env
#     volumes:
#       - ./backend:/var/www/html

#   db:
#     image: mysql:8
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: Rushi@123
#       MYSQL_DATABASE: app_db
#       MYSQL_USER: rushi
#       MYSQL_PASSWORD: Rushi@234
#     ports:
#       - "3307:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

#   frontend:
#     build: ./front-end
#     container_name: frontend_app
#     ports:
#       - "3000:80"
#     volumes:
#       - ./front-end:/usr/share/nginx/html
#     depends_on:
#       - backend
#     restart: always

#   user_setup:
#     build: ./user_setup
#     container_name: user_setup
#     depends_on:
#       - db
#       - backend
#     environment:
#       MYSQL_HOST: mysql_db
#       MYSQL_PORT: 3306
#       MYSQL_USER: rushi
#       MYSQL_PASSWORD: Rushi@234
#       MYSQL_DATABASE: app_db
#     restart: "no"

# volumes:
#   db_data:

version: '3.8'

services:
  backend:
    build: ./backend
    container_name: php_backend
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - ./env
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rushi@123
      MYSQL_DATABASE: app_db
      MYSQL_USER: rushi
      MYSQL_PASSWORD: Rushi@234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./front-end
    container_name: frontend_app
    ports:
      - "3000:443"  # Expose HTTPS port 443
    volumes:
      - ./front-end:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always

  user_setup:
    build: ./user_setup
    container_name: user_setup
    depends_on:
      - db
      - backend
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: rushi
      MYSQL_PASSWORD: Rushi@234
      MYSQL_DATABASE: app_db
    restart: "no"

volumes:
  db_data:
